### ISSUE TITLE
issues running java:build

### ISSUE THREAD

**Issue by stepheneb** [kevwil/aspen#1]
Hi Kevin,

A note about how I got java:build to work.

Initially running:

```
$ jruby -S rake java:build
```

stopped and told me that I needed:

```
org.jruby:jruby:jar:1.4.0
org.jboss.netty:netty:jar:3.1.5.GA
```

Would be nice if the build task resolved these dependencies.

I installed them like this:

```
cd javalib/
mvn compile
cd ..
```

But java:build still wouldn't complete because I was missing junit. So I installed it the same way:

```
cd javalib/
mvn test
cd ..
```

Now java:build runs.

**Comment by kevwil** [comment]
I sometimes work offline, so the task calls Maven in offline mode. In offline mode, unresolved dependencies are not automatically downloaded and installed into your local Maven repository. I've found that if I accidentally run Maven in regular mode but when not connected to the Internet, unresolved dependencies cause the world to melt and life as we know it to cease to exist.

I will add a note in the README about 'offline mode'. Thanks for catching this!

**Comment by stepheneb** [comment]
I sent another pull request with added development instructions in the README -- perhaps useful to merge.

**Comment by kevwil** [comment]
I've never had a pull request before, not sure how to do that. Since I was working on the README file as well, I imagine the merge might be difficult. I've tried to capture what you added in my changes, though.
